export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REG_ROUTE = '/registration' 
export const NEWS_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const NEWSPAGE_ROUTE = '/newspage'